Gemfile, Gemfile.lock
Añado gemas tiny_tds y activerecord-sqlserver-adapter para poder conectar con la base de datos SQL Server
=> Añado gemas tiny_tds y activerecord-sqlserver-adapter

.gitignore
incluir fichero yml en gitignore.
=> incluir fichero yml en gitignore.

Gemfile, Gemfile.lock, app/controllers/t_usuarios_controller.rb, app/models/t_usuario.rb, app/views/t_usuarios/index.html.erb, test/models/t_usuario_test.rb
Uso de la gema bcrypt para poder implementar la seguridad por password (hacer bundle install)
Añadimos en la base de datos de desarrollo un campo denominado password_digest
Incluye nuevos campos de consulta.
Modificaciones en el index.html.erb para hacer más presentable 
Incluye un combo con opciones para el campo booleano
=> Modificaciones en el modelo t_usuarios para el uso de passwords

app/controllers/t_usuarios_controller.rb, app/models/t_usuario.rb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/t_usuarios/_form.html.erb, app/views/t_usuarios/index.html.erb, app/views/t_usuarios/new.html.erb, db/schema.rb, test/models/t_usuario_test.rb
* Modificaciones para las altas de usuario con password
* El combo de usuarios Activos NO funciona para el alta, hay que revisarlo
* Modificaciones en el header del proyecto
=> Alta de usuarios con password

app/assets/javascripts/sessions.coffee, app/assets/javascripts/static_pages.coffee, app/assets/stylesheets/sessions.scss, app/assets/stylesheets/static_pages.scss, app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, app/controllers/static_pages_controller.rb, app/controllers/t_sedes_controller.rb, app/controllers/t_usuarios_controller.rb, app/helpers/sessions_helper.rb, app/helpers/static_pages_helper.rb, app/views/layouts/_header.html.erb, app/views/layouts/_shim.html.erb, app/views/layouts/application.html.erb, app/views/sessions/new.html.erb, app/views/static_pages/main.html.erb, config/routes.rb, test/controllers/sessions_controller_test.rb, test/controllers/static_pages_controller_test.rb
* Incluye las modifcaciones necesarias para implementar la session de la aplicación
* Comprueba que la session este establecida correctamente para que se pueda navegar por la aplicación
=> Gestión de inicio de sesión de la aplicación

Gemfile.lock, app/assets/stylesheets/custom2016.scss, app/assets/stylesheets/sessions.scss, app/views/sessions/new.html.erb
Se modifica la vista de la pantalla de login
=> Se modifica la vista de la pantalla de login

app/assets/javascripts/t_contajes.coffee, app/assets/stylesheets/custom2016.scss, app/assets/stylesheets/scaffolds.scss, app/assets/stylesheets/t_contajes.scss, app/controllers/sessions_controller.rb, app/controllers/t_contajes_controller.rb, app/helpers/t_contajes_helper.rb, app/models/t_contaje.rb, app/views/layouts/_footer.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/static_pages/main.html.erb, app/views/t_contajes/_form.html.erb, app/views/t_contajes/_t_contaje.json.jbuilder, app/views/t_contajes/edit.html.erb, app/views/t_contajes/index.html.erb, app/views/t_contajes/index.json.jbuilder, app/views/t_contajes/new.html.erb, app/views/t_contajes/show.html.erb, app/views/t_contajes/show.json.jbuilder, config/routes.rb, test/controllers/t_contajes_controller_test.rb, test/fixtures/t_contajes.yml, test/models/t_contaje_test.rb
Introducción de contajes en pagina principal
Maquetación del menú
Introducción usuarios y cerrar sesion en el pie de pagina
=> Introducción de contajes en pagina principal

app/views/layouts/_header.html.erb, app/views/t_contajes/index.html.erb
=> correción de errores

app/assets/javascripts/t_contajes.coffee, app/assets/stylesheets/t_contajes.scss, app/controllers/t_contajes_controller.rb, app/views/layouts/application.html.erb, app/views/t_contajes/index.html.erb
actualización de datos moviles,fija y electronica automaticamente cada 10s
=> actualización de datos moviles,fija y electronica automaticamente cada 10s

app/assets/javascripts/application.js, app/assets/javascripts/t_contajes.js, app/assets/stylesheets/custom2016.scss, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/t_contajes/index.html.erb
Actualización de datos de contajes controlando la petición de datos si no se está visualizando la pagina principal
=>  Actualización de datos de contajes controlando la petición de datos si no se está visualizando la pagina principal

app/controllers/welcome_controller.rb, config/initializers/session_store.rb
- Arregla también una errata en welcome_controller.rb
=> Ajuste de Session :expire_after

app/assets/javascripts/t_contajes.js, app/assets/stylesheets/t_fechas_carga.scss, app/controllers/welcome_controller.rb, app/views/layouts/application.html.erb, app/views/welcome/_t_fechas_carga.html.erb, app/views/welcome/_t_fechas_carga_datos.html.erb
Se muestran las fechas de carga en la pantalla principal, con ficheros randerizados
=>  Se muestran las fechas de carga en la pantalla principal, con ficheros randerizados

Gemfile, Gemfile.lock, app/controllers/t_sedes_controller.rb, app/views/t_sedes/index.html.erb, app/views/t_sedes/show.html.erb
- Incluye la Gema Ransack que permite la ordenación por nombre de columnas y facilidades en las búsquedas.
- Pruebas con Google Maps para el posicionamiento de Sedes
=> Ransack y Maps

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/_settings.scss, app/assets/stylesheets/application.css, app/assets/stylesheets/foundation_and_overrides.scss, app/views/layouts/application.html.erb
Implementamos Foundation.
(Perdemos parte del código del layout y el js de application)
=> Implementamos Foundation

app/assets/stylesheets/_settings.scss, app/assets/stylesheets/custom2016.scss, app/controllers/sessions_controller.rb, app/views/layouts/_footer.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/_menu.html.erb, app/views/layouts/application.html.erb
implementación del menú con foundation
=> implementación del menú con foundation

app/models/t_edificio.rb, app/models/t_sede.rb, app/views/t_sedes/show.html.erb
Implementación de los datos del edificio SAP en el detalle de las sedes
=> Implementación de los datos del edificio SAP en el detalle de las sedes

app/views/t_sedes/show.html.erb
maquetación de la vista de la sede para responsive
=> maquetación de la vista de la sede para responsive

app/views/t_sedes/_form.html.erb, app/views/t_sedes/_t_sede.json.jbuilder, app/views/t_sedes/edit.html.erb, app/views/t_sedes/new.html.erb, app/views/t_sedes/show.html.erb, app/views/t_usuarios/show.html.erb
- Organización de ficheros en sedes renderizando ficheros de edición y alta.
- Habilitar la función de edición de una sede.
=> Organización de ficheros en sedes renderizando ficheros de edición y alta

app/assets/stylesheets/custom2016.scss, app/controllers/t_acronimos_sede_edrs_controller.rb, app/controllers/t_sedes_controller.rb, app/helpers/t_acronimos_sede_ed_rs_helper.rb, app/helpers/t_acronimos_sede_edr_helper.rb, app/models/t_acronimos_sede_edr.rb, app/views/layouts/_header.html.erb, app/views/layouts/_menu.html.erb, app/views/t_acronimos_sede_edrs/_form.html.erb, app/views/t_acronimos_sede_edrs/edit.html.erb, app/views/t_acronimos_sede_edrs/index.html.erb, app/views/t_acronimos_sede_edrs/new.html.erb, app/views/t_acronimos_sede_edrs/show.html.erb, config/locales/activerecord.es.yml, config/routes.rb, spec/factories/factories.rb, spec/helpers/t_acronimos_sede_edr_helper_spec.rb, spec/models/t_acronimos_sede_edr_spec.rb
implementación del apartado de acrónimos
=> implementación del apartado de acrónimos

app/views/lin_moviles/_search.html.erb
Añade diferentes campos de búsqueda aunque mantiene la búsqueda genérica.
=> Mejoras formulario de búsqueda LinMoviles
